<?php

function acf_mass_times()
{
    return array(
        array(
            'key' => 'field_65b947300ad11',
            'label' => 'Mass/Mission',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            // 'conditional_logic' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_626c37cd602a4',
                        'operator' => '!=',
                        'value' => 'slider',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_65b9473e0ad12',
            'label' => 'Image 1',
            'name' => 'mass_times_image_1',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
        ),
        array(
            'key' => 'field_65b947580ad13',
            'label' => 'Image 2',
            'name' => 'mass_times_image_2',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'medium',
        ),
        array(
            'key' => 'field_65b9475c0ad14',
            'label' => 'Headline',
            'name' => 'mass_times_headline_1',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '*Max 20 characters',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '20',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_65b947840ad16',
            'label' => 'Link',
            'name' => 'mass_times_link',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_65cfaddc22530',
            'label' => 'Content Type',
            'name' => 'mass_times_content_type',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '*Choose if you want to display a free text area or your mass times',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui_on_text' => 'Mass Times',
            'ui_off_text' => 'Textarea',
            'ui' => 1,
        ),
        array(
            'key' => 'field_65dcfeed09c98',
            'label' => 'Background Image',
            'name' => 'mass_times_bg_img',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '21',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'dove' => 'Dove',
                'lamb' => 'Lamb',
                'hand' => 'Hand',
                'select' => 'Select ->',
            ),
            'default_value' => "dove",
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 1,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6182f5a5311cz',
            'label' => 'Watermark Upload',
            'name' => 'watermark_upload',
            'type' => 'file',
            'instructions' => 'Recommended size 750x750.',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65dcfeed09c98',
                        'operator' => '==',
                        'value' => 'select',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '21',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_65b94794b4ef8',
            'label' => 'Mass Times',
            'name' => '',
            'aria-label' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65cfaddc22530',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Edit mass times <a href="/wp-admin/admin.php?page=theme-general-settings">here</a>',
            'new_lines' => 'wpautop',
            'esc_html' => 0,
        ),
        array(
            'key' => 'field_65cfae7e22531',
            'label' => 'Content',
            'name' => 'mass_times_content',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65cfaddc22530',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
            'delay' => 0,
        ),
    );
}
