<?php

function acf_parishes()
{
    return array(
  		array(
  			'key' => 'field_626c37b2602a3',
  			'label' => 'Parish Cluster',
  			'name' => '',
  			'type' => 'tab',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => 0,
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'placement' => 'top',
  			'endpoint' => 0,
  		),
  		array(
  			'key' => 'field_626c37cd602a4',
			'label' => 'Cluster Style',
			'name' => 'cluster_style',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'buttons' => 'Buttons',
				'carousel' => 'Carousel',
				'slider' => 'Slider - <b>Note this will move Mass Times option from Theme Settings to here.</b>',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
  		),
  		array(
  			'key' => 'field_6270a5d99e494',
  			'label' => 'Parish Cluster Title',
  			'name' => 'parish_scroll_title',
  			'type' => 'text',
  			'instructions' => '*Max 25 Characters',
  			'required' => 0,
  			'conditional_logic' => 0,
  			// 'conditional_logic' => array(
  			// 	array(
  			// 		array(
  			// 			'field' => 'field_626c37cd602a4',
  			// 			'operator' => '!=',
  			// 			'value' => 'slider',
  			// 		),
  			// 	),
  			// ),
  			'wrapper' => array(
  				'width' => '50',
  				'class' => '',
  				'id' => '',
  			),
  			'default_value' => '',
  			'placeholder' => '',
  			'prepend' => '',
  			'append' => '',
  			'maxlength' => '25',
  		),
  		array(
  			'key' => 'field_626c3734abd52',
  			'label' => 'Parish Buttons',
  			'name' => 'parish_buttons',
  			'type' => 'repeater',
  			'instructions' => '',
  			'required' => 0,
  			'conditional_logic' => array(
  				array(
  					array(
  						'field' => 'field_626c37cd602a4',
  						'operator' => '==',
  						'value' => 'buttons',
  					),
  				),
  			),
  			'wrapper' => array(
  				'width' => '',
  				'class' => '',
  				'id' => '',
  			),
  			'collapsed' => '',
  			'min' => 0,
  			'max' => 0,
  			'layout' => 'table',
  			'button_label' => '',
  			'sub_fields' => array(
  				array(
  					'key' => 'field_626c3747abd53',
  					'label' => 'Image',
  					'name' => 'image',
  					'type' => 'image',
  					'instructions' => 'Recommended aspect ratio 370 / 305.',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'return_format' => 'url',
  					'preview_size' => 'medium',
  					'library' => 'all',
  					'min_width' => '',
  					'min_height' => '',
  					'min_size' => '',
  					'max_width' => '',
  					'max_height' => '',
  					'max_size' => '',
  					'mime_types' => '',
  				),
        		array(
        			'key' => 'field_626c3734abd5z',
        			'label' => 'Mass Times',
        			'name' => 'mass_times',
        			'type' => 'repeater',
        			'instructions' => 'Character limit 30.',
        			'required' => 0,
        			'wrapper' => array(
        				'width' => '',
        				'class' => '',
        				'id' => '',
        			),
        			'collapsed' => '',
        			'min' => 0,
        			'max' => 3,
        			'layout' => 'table',
        			'button_label' => '',
        			'sub_fields' => array(
        				array(
        					'key' => 'field_626c3773abd54',
        					'label' => 'Time',
        					'name' => 'text',
        					'type' => 'text',
        					'instructions' => '',
        					'required' => 0,
        					'conditional_logic' => 0,
        					'wrapper' => array(
        						'width' => '',
        						'class' => '',
        						'id' => '',
        					),
        					'default_value' => '',
        					'placeholder' => '',
        					'maxlength' => 30,
        					'rows' => '',
        					'new_lines' => '',
        				),
				      ),
          		),
  				array(
  					'key' => 'field_626c3773abd5z',
  					'label' => 'Title',
  					'name' => 'title',
  					'type' => 'text',
  					'instructions' => 'Character limit 20.',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'default_value' => '',
  					'placeholder' => '',
  					'maxlength' => 20,
  					'rows' => '',
  					'new_lines' => '',
  				),
  				array(
  					'key' => 'field_626c379dabd55',
  					'label' => 'Link',
  					'name' => 'link',
  					'type' => 'link',
  					'instructions' => 'Please note the Title field will display instead of the link text.',
  					'required' => 0,
  					'conditional_logic' => 0,
  					'wrapper' => array(
  						'width' => '',
  						'class' => '',
  						'id' => '',
  					),
  					'return_format' => 'array',
  				),
  			),
  		),
		array(
			'key' => 'field_65f19df8329dz',
			'label' => 'Carousel',
			'name' => 'parish_carousel',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_626c37cd602a4',
						'operator' => '==',
						'value' => 'carousel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Parish',
			'sub_fields' => array(
				array(
                    'key' => 'field_60f1e107bcf37',
                    'label' => 'Icon Type',
                    'name' => 'is_image',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => 'Image',
                    'ui_off_text' => 'FA Icon',
                ),
                array(
                    'key' => 'field_60f1e1b3bcf39',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_60f1e107bcf37',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_60f1e136bcf38',
                    'label' => 'FA Icon',
                    'name' => 'fa_icon',
                    'type' => 'font-awesome',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_60f1e107bcf37',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'icon_sets' => array(
                        0 => 'fas',
                        1 => 'far',
                        2 => 'fab',
                    ),
                    'custom_icon_set' => '',
                    'default_label' => '',
                    'default_value' => '',
                    'save_format' => 'element',
                    'allow_null' => 0,
                    'show_preview' => 1,
                    'enqueue_fa' => 0,
                    'fa_live_preview' => '',
                    'choices' => array(),
                ),
				array(
					'key' => 'field_65f19e2a329dz',
					'label' => 'Parish Name',
					'name' => 'parish_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_65f19df8329dz',
				),
				array(
					'key' => 'field_626c379dabd5y',
					'label' => 'Button',
					'name' => 'button',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				array(
					'key' => 'field_65f19e4b329dz',
					'label' => 'Content',
					'name' => 'content',
					'aria-label' => '',
					'type' => 'textarea',
                    'instructions' => '*Max 200 characters',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => 200,
                    'rows' => 4,
                    'new_lines' => 'br',
                ),
			),
		),
        // array(
        //     'key' => 'field_65b9475c0ad1y',
        //     'label' => 'Headline',
        //     'name' => 'cluster_mass_times_headline_1',
        //     'aria-label' => '',
        //     'type' => 'text',
        //     'instructions' => '*Max 20 characters',
        //     'required' => 0,
		// 	'conditional_logic' => array(
		// 		array(
		// 			array(
		// 				'field' => 'field_626c37cd602a4',
		// 				'operator' => '==',
		// 				'value' => 'slider',
		// 			),
		// 		),
		// 	),
        //     'wrapper' => array(
        //         'width' => '50',
        //         'class' => '',
        //         'id' => '',
        //     ),
        //     'default_value' => '',
        //     'maxlength' => '20',
        //     'placeholder' => '',
        //     'prepend' => '',
        //     'append' => '',
        // ),
        array(
            'key' => 'field_65dcfeed09c9z',
            'label' => 'Background Image',
            'name' => 'cluster_mass_times_bg_img',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '21',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'dove' => 'Dove',
                'lamb' => 'Lamb',
                'hand' => 'Hand',
                'select' => 'Select ->',
            ),
            'default_value' => "dove",
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 1,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6182f5a5311cy',
            'label' => 'Watermark Upload',
            'name' => 'cluster_watermark_upload',
            'type' => 'file',
            'instructions' => 'Recommended size 750x750.',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_65dcfeed09c9z',
                        'operator' => '==',
                        'value' => 'select',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '21',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
		array(
			'key' => 'field_61a917aeb95ez',
			'label' => 'Slider',
			'name' => 'parish_slider',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '*Min. 2, Max. 7',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_626c37cd602a4',
						'operator' => '==',
						'value' => 'slider',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 2,
			'max' => 7,
			'collapsed' => '',
			'button_label' => 'Add Parish',
			'rows_per_page' => 20,
			'sub_fields' => array(
                array(
                    'key' => 'field_65b9473e0ad1z',
                    'label' => 'Image 1',
                    'name' => 'mass_times_image_1p',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_65b947580ad1y',
                    'label' => 'Image 2',
                    'name' => 'mass_times_image_2p',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_65b9475c0ad1z',
                    'label' => 'Parish Name',
                    'name' => 'parish_slider_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '*Max 20 characters',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '20',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_61a917aeb95ey',
                    'label' => 'Buttons',
                    'name' => 'mass_times_buttons',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 2,
                    'collapsed' => '',
                    'button_label' => 'Add Button',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_65b947840ad1z',
                            'label' => 'Button',
                            'name' => 'cluster_mass_times_link',
                            'aria-label' => '',
                            'type' => 'link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'parent_repeater' => 'field_61a917aeb95ey',
                        ),
                    ),
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_65cfaddc2253z',
                    'label' => 'Content Type',
                    'name' => 'cluster_mass_times_content_type',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '*Choose if you want to display a free text area or your mass times',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui_on_text' => 'Mass Times',
                    'ui_off_text' => 'Textarea',
                    'ui' => 1,
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_65cfae7e2253z',
                    'label' => 'Content',
                    'name' => 'cluster_mass_times_content',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_65cfaddc2253z',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
                array(
                    'key' => 'field_61a917aeb95eq',
                    'label' => 'Sections',
                    'name' => 'cluster_mass_times_sections',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_65cfaddc2253z',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'row',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'field_65cbaaf06097z',
                    'button_label' => 'Add Day',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_65cbaaf06097z',
                            'label' => 'Title',
                            'name' => 'title',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '*Max. 50 characters',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_65cfaddc2253z',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => 50,
                            'placeholder' => 'Weekends/Weekdays/Reconciliation',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_61a917aeb95eq',
                        ),
                        array(
                            'key' => 'field_65cbab546097z',
                            'label' => 'Times',
                            'name' => 'times',
                            'aria-label' => '',
                            'type' => 'repeater',
                            'instructions' => '*Max. 4 times',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'field_65cfaddc2253z',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'table',
                            'min' => 1,
                            'max' => 4,
                            'collapsed' => 'field_65cbaba16097z',
                            'button_label' => 'Add Time',
                            'rows_per_page' => 20,
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_65cbaba16097z',
                                    'label' => 'Day',
                                    'name' => 'day',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => 'Monday',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_65cbab546097z',
                                ),
                                array(
                                    'key' => 'field_65cbabe16097z',
                                    'label' => 'Times',
                                    'name' => 'day_times',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '5:15 pm',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_65cbab546097z',
                                ),
                                array(
                                    'key' => 'field_65cbac246097z',
                                    'label' => 'Languages',
                                    'name' => 'languages',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '*optional',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => 'española',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_65cbab546097z',
                                ),
                                array(
                                    'key' => 'field_65cbac6a6097z',
                                    'label' => 'Additional Notes',
                                    'name' => 'additional_notes',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '*optional',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => 'or by appointment',
                                    'prepend' => '',
                                    'append' => '',
                                    'parent_repeater' => 'field_65cbab546097z',
                                ),
                            ),
                            'parent_repeater' => 'field_61a917aeb95eq',
                        ),
                    ),
                    'parent_repeater' => 'field_61a917aeb95ez',
                ),
            ),
        ),
  	);
}
